#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"

CONTAINER_NAME="rethinkdb_$APP"
VOLUME_DIR="$DOKKU_ROOT/$APP/rethinkdb"

if [[ -d "$VOLUME_DIR" ]]; then
  echo "$STDIN --link $CONTAINER_NAME:rethinkdb_link"
fi
