#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

RETHINKDB_IMAGE=rethinkdb:2.0.4

PENDING_DIR="$DOKKU_ROOT/.rethinkdb/pending-volumes"

mkdir -p "$PENDING_DIR"
chown -R dokku:dokku "$PENDING_DIR"

docker pull $RETHINKDB_IMAGE
