#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

RETHINKDB_IMAGE=crosbymichael/rethinkdb

CONTAINER_NAME="rethinkdb/$APP"
VOLUME_DIR="$DOKKU_ROOT/$APP/rethinkdb"

if [[ -d "$VOLUME_DIR" ]]; then
    echo "-----> Starting linked container $CONTAINER_NAME ..."
    dokku rethinkdb:start $APP
fi
