#!/usr/bin/env bash
set -e; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

CONTAINER_NAME="rethinkdb_$APP"

# Kill any existing RethinkDB container for this app
ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
if [[ ! -z $ID ]]; then
    docker kill $ID > /dev/null
    docker rm $ID > /dev/null
fi

# Any volume will be deleted with the app
