#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

CONTAINER_NAME="rethinkdb_$APP"
VOLUME_DIR="$DOKKU_ROOT/$APP/rethinkdb"

if [[ -d "$VOLUME_DIR" ]]; then
    echo "-----> Starting linked container $CONTAINER_NAME ..."
    dokku rethinkdb:start $APP
    dokku rethinkdb:info $APP
fi
