#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

CONTAINER_NAME="rethinkdb_$APP"

docker_get_id() {
    local CID=`docker inspect '-f={{.Id}}' "$1" 2> /dev/null || true`
    if [[ "$CID" == "<no value>" ]]; then
      CID=`docker inspect '-f={{.ID}}' "$1" 2> /dev/null || true`
    fi
    echo "$CID"
}

# Kill any existing RethinkDB container for this app
ID=$(docker_get_id "$CONTAINER_NAME")
if [[ ! -z $ID ]]; then
    docker kill $ID > /dev/null
    docker rm $ID > /dev/null
fi

# Any volume will be deleted with the app
